# Generated by Django 5.1 on 2024-09-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='biography',
            field=models.TextField(blank=True, default='', max_length=512),
            preserve_default=False,
        ),
    ]
